# Generated by Django 3.2.7 on 2021-09-24 13:12

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage('media'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
